name: Trigger auto deployment for backend-container-34

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ stage-10 ]
    paths:
    - '**'
    - '.github/workflows/backend-container-34-AutoDeployTrigger-a1bda7ca-b13d-4b96-acb7-a67ccf173149.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKENDCONTAINER34_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKENDCONTAINER34_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKENDCONTAINER34_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: finalstagecontainer.azurecr.io
          registryUsername: ${{ secrets.BACKENDCONTAINER34_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKENDCONTAINER34_REGISTRY_PASSWORD }}
          containerAppName: backend-container-34
          resourceGroup: stage10
          imageToBuild: finalstagecontainer.azurecr.io/backend-container-34:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


